import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { cn } from "@/lib/utils";
import Navbar from '@/components/Navbar';
import Providers from '@/components/Providers';
import { Toaster } from 'sonner';
import Headers from '@/components/home/Header';
import Nav from '@/components/Nav';
import Footer from "@/components/home/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="">
      <body className="">
          <Providers>
            <div className="fixed left-0 top-0 -z-10 h-full w-full">
              <div className="relative h-full w-full bg-black">
                <div className="absolute bottom-0 left-0 right-0 top-0 bg-[linear-gradient(to_right,#4f4f4f2e_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:14px_24px]" />
                <div className="absolute left-0 right-0 top-[-10%] h-[1000px] w-[1000px] rounded-full bg-[radial-gradient(circle_400px_at_50%_300px,#fbfbfb36,#000)]" />
              </div>
            </div>    
            <main className="relative mx-auto h-screen w-full max-w-7xl px-6 md:px-8 lg:px-12">
              <Headers />
              {children}
              </main>
          </Providers>
          <Toaster position='top-center' richColors />
      </body>
    </html>
  );
}
